# Application configuration
app:
  # Security configuration
  jwt:
    secret: lkjsDf079283alkjsd9a0sd6fasljj-jalZXFfa
  security:
    permitall: false
    maximumLoginAttempts: 3
    loginAttemptsExpiration: 5
logging:
  level:
    io.dpopkov.knowthenix.ums.services: trace
    io.dpopkov.knowthenix.ums.listeners: trace

# Path to the error controller may be customized
server:
  error:
    path: /error
